name: list-path
on: [push]
jobs:
  ls-path:
    runs-on: ubuntu-20.04
    steps:
      - run: echo $PATH
      - shell: bash
        run: echo $PATH|while IFS= read -rd:;do find $REPLY||true;done;true
      - run: cat /usr/local/bin/README.md
      - run: python3 -c 'import lxml'
      - run: which python3
      - run: python3 -m pip --version
